// Domyślne treści (przykładowe, do podmiany przez klientkę) — strona wygląda
// kompletnie także wtedy, gdy pobranie danych z Sanity zawiedzie.
// Ten sam zestaw jest źródłem seedu do Sanity (scripts/seed.mjs).



/**
 * Buduje Portable Text z prostej listy [styl, tekst, opcje].
 *
 * Opcje obsługują to, czego wymaga treść klientki w opisie pielęgnacji twarzy:
 * `listItem: 'bullet'` robi z akapitu punkt listy, `marks: ['strong']` wytłuszcza
 * etykietę nad listą („Wskazania", „Efekty zabiegowe").
 */
export function blocks(id, lines) {
  return lines.map(([style, text, opcje = {}], i) => ({
    _type: 'block',
    _key: `${id}-${i}`,
    style,
    ...(opcje.listItem ? { listItem: opcje.listItem, level: 1 } : {}),
    markDefs: [],
    children: [
      { _type: 'span', _key: `${id}-${i}-s`, text, marks: opcje.marks || [] },
    ],
  }))
}

export const STOCK = {
  face: 'https://images.pexels.com/photos/3985329/pexels-photo-3985329.jpeg?auto=compress&cs=tinysrgb&w=1200',
  laser: 'https://images.pexels.com/photos/4672470/pexels-photo-4672470.jpeg?auto=compress&cs=tinysrgb&w=1200',
  laserWide: 'https://images.pexels.com/photos/35103880/pexels-photo-35103880.jpeg?auto=compress&cs=tinysrgb&w=1200',
  slide1: 'https://images.pexels.com/photos/7750099/pexels-photo-7750099.jpeg?auto=compress&cs=tinysrgb&w=1400',
  slide2: 'https://images.pexels.com/photos/35103880/pexels-photo-35103880.jpeg?auto=compress&cs=tinysrgb&w=1400',
  slide3: 'https://images.pexels.com/photos/4672470/pexels-photo-4672470.jpeg?auto=compress&cs=tinysrgb&w=1400',
  main: 'https://images.pexels.com/photos/6899550/pexels-photo-6899550.jpeg?auto=compress&cs=tinysrgb&w=1600',
  about: 'https://images.pexels.com/photos/3997379/pexels-photo-3997379.jpeg?auto=compress&cs=tinysrgb&w=1200',
  voucher: 'https://images.pexels.com/photos/6634871/pexels-photo-6634871.jpeg?auto=compress&cs=tinysrgb&w=1200',
  gal: [
    'https://images.pexels.com/photos/4672470/pexels-photo-4672470.jpeg?auto=compress&cs=tinysrgb&w=900',
    'https://images.pexels.com/photos/3985329/pexels-photo-3985329.jpeg?auto=compress&cs=tinysrgb&w=900',
    'https://images.pexels.com/photos/6899550/pexels-photo-6899550.jpeg?auto=compress&cs=tinysrgb&w=900',
    'https://images.pexels.com/photos/35103880/pexels-photo-35103880.jpeg?auto=compress&cs=tinysrgb&w=900',
    'https://images.pexels.com/photos/13068361/pexels-photo-13068361.jpeg?auto=compress&cs=tinysrgb&w=900',
    'https://images.pexels.com/photos/7750099/pexels-photo-7750099.jpeg?auto=compress&cs=tinysrgb&w=900',
    'https://images.pexels.com/photos/36930886/pexels-photo-36930886.jpeg?auto=compress&cs=tinysrgb&w=900',
    'https://images.pexels.com/photos/3997379/pexels-photo-3997379.jpeg?auto=compress&cs=tinysrgb&w=900',
  ],
}

export const settings = {
  salonName: 'ZJAWISKOWO',
  salonSubtitle: 'Salon kosmetyczny · Depilacja laserowa',
  trustKicker: 'Dlaczego ZJAWISKOWO',
  trustHeading: 'Co wyróżnia mój salon',
  showTrust: true,
  reviewsKicker: 'Opinie klientek',
  reviewsHeading: 'Co mówią klientki',
  showReviews: true,
  theme: 'gold',
  heroKicker: 'Salon kosmetyczny · Depilacja laserowa · Krzeszowice',
  tagline: 'Piękno zaczyna się tutaj',
  heroLead:
    'Kameralny salon w Krzeszowicach, w którym depilacja laserowa spotyka się ze spokojną, dobrze dobraną pielęgnacją twarzy. Prowadzę go sama, więc od konsultacji po ostatni zabieg w serii jesteś w tych samych rękach.',
  phone: '517 899 229',
  pillarsKicker: 'Oferta salonu',
  pillarsHeading: 'Dwa filary ZJAWISKOWO',
  pillarsLead:
    'Depilacja laserowa i pielęgnacja twarzy. Dwie ścieżki, które prowadzę osobno albo łączę, zależnie od tego, czego potrzebuje Twoja skóra.',
  galleryKicker: 'Galeria',
  galleryHeading: 'Zabiegi',
  showGallery: true,
  showFaq: true,
  ctaHeading: 'Umów wizytę',
  ctaLead:
    'Najprościej zadzwonić. Porozmawiamy o Twojej skórze, dobierzemy zabieg i znajdziemy termin, który Ci pasuje.',
  showPromo: true,
  promoText: 'Do 1200 zł oszczędności przy pakietach depilacji · −20% na pielęgnację twarzy · Sprawdzaj inne promocje na FB ZJAWISKOWO',
  address: 'ul. 3 Maja [numer do uzupełnienia], 32-065 Krzeszowice',
  hours: 'poniedziałek – piątek 8:00 – 20:00 · sobota 9:00 – 13:00',
  contactNotes: [
    'Bezpłatny parking',
    'Budynek przy automyjni',
    'Wejście od strony parkingu',
  ],
  googleMapsEmbedUrl:
    'https://www.google.com/maps?q=ul.%203%20Maja%2C%20Krzeszowice&output=embed',
  facebookUrl: '#',
  instagramUrl: '#',
  domain: 'zjawiskowo.com.pl',
  footerNote:
    'Zasady korzystania z usług opisuje regulamin salonu, a informacje o danych osobowych i plikach cookies znajdziesz w polityce prywatności.',
}

/* ── Zabiegi ─────────────────────────────────────────────────────────── */

const laserDescription = blocks('laser', [
  ['normal',
    'Depilacja laserowa opiera się na zjawisku fototermolizy selektywnej. Wiązka światła jest pochłaniana przede wszystkim przez melaninę, czyli barwnik zawarty we włosie i w mieszku włosowym, a nie przez otaczającą skórę. Pochłonięta energia zamienia się w ciepło, które oddziałuje na struktury odpowiedzialne za odrastanie włosa. Najlepiej reagują włosy ciemne i grube przy jaśniejszej skórze; włosy bardzo jasne, rude i siwe zawierają mało melaniny, więc efekt bywa u nich niewielki.'],
  ['h3',
    'Dlaczego zabiegi wykonuje się w serii'],
  ['normal',
    'Laser działa skutecznie tylko na włosy będące w fazie aktywnego wzrostu, a w danym momencie znajduje się w niej zaledwie część owłosienia na danym obszarze. Dlatego jeden zabieg z założenia nie obejmuje wszystkich włosów, a kolejne wizyty trafiają w te, które w międzyczasie weszły w fazę wzrostu. U większości osób pełna seria to około ośmiu zabiegów, zależnie od partii ciała, koloru i grubości włosa oraz uwarunkowań hormonalnych.'],
  ['h3',
    'Laser na miejscu, terminy bez przerw'],
  ['normal',
    'Laser stoi na miejscu w Krzeszowicach i jest dostępny każdego dnia pracy salonu, więc kolejne wizyty umawiam w terminie, który Ci pasuje, bez czekania na wolny sprzęt. To ma znaczenie praktyczne: seria działa najlepiej wtedy, gdy odstępy między zabiegami są zachowane. Zbyt krótka przerwa oznacza pracę na włosach poza fazą wzrostu, zbyt długa pozwala części mieszków przejść cały cykl. Odstęp między kolejnymi zabiegami wynosi zazwyczaj pięć tygodni.'],
  ['h3',
    'Jak przygotować się do wizyty'],
  ['normal',
    'Obszar zabiegu wygol maszynką na 12 do 24 godzin przed wizytą. Przez co najmniej cztery tygodnie wcześniej i przez cały czas trwania serii nie usuwaj włosów z cebulką, czyli woskiem, pastą cukrową, depilatorem ani pęsetą, bo laser potrzebuje włosa w mieszku. Na dwa do czterech tygodni przed zabiegiem odstaw opalanie i solarium, a samoopalacze zmyj całkowicie. Kwasy, retinol i preparaty złuszczające warto odstawić około miesiąca wcześniej. Jeżeli przyjmujesz leki, które mogą uwrażliwiać na światło, powiedz o tym przed zabiegiem; decyzję o jakiejkolwiek zmianie w leczeniu podejmuje wyłącznie Twój lekarz.'],
  ['h3',
    'Po zabiegu'],
  ['normal',
    'Przez kilka dni odpuść saunę, gorące kąpiele, basen i intensywny wysiłek. Skórę myj łagodnie, nawilżaj i chroń wysokim filtrem przez cały czas trwania serii, bo to zmniejsza ryzyko przebarwień. Między zabiegami wolno wyłącznie golić. Potraktowane włosy wypadają stopniowo w ciągu kilku do kilkunastu dni, co bywa mylone z odrastaniem.'],
  ['h3',
    'Odczucia i przeciwwskazania'],
  ['normal',
    'W trakcie zabiegu odczuwa się zwykle ciepło i delikatne ukłucia, mocniej w partiach wrażliwych. Po zabiegu skóra bywa zaczerwieniona i rozgrzana, u większości osób ustępuje to w ciągu jednego do trzech dni; indywidualna wrażliwość bywa różna. Zabieg wyklucza między innymi ciąża i karmienie piersią, świeża opalenizna oraz samoopalacz na skórze, aktywne infekcje i zmiany skórne w miejscu zabiegu, przyjmowanie retinoidów i leków fotouczulających, padaczka, rozrusznik serca i choroby nowotworowe. Lista ma charakter orientacyjny: przed pierwszą wizytą przeprowadzam wywiad, a część stanów zdrowia wymaga wcześniejszej konsultacji lekarskiej. Pierwszy zabieg może być poprzedzony próbą laserową.'],
])

const twarzDescription = blocks('twarz', [
  ['normal',
    'Pielęgnacja twarzy w ZJAWISKOWO zaczyna się od rozmowy i oceny skóry, a dopiero potem od wyboru zabiegu. Ta sama cera potrzebuje czegoś innego w lutym, a czegoś innego w lipcu, więc protokół układam pod bieżący stan skóry, nie pod nazwę usługi z cennika. Większość zabiegów pracuje najlepiej w serii, z zachowaniem odstępów.'],
  ['h3',
    'Oczyszczanie wodorowe PREMIUM'],
  ['normal',
    'I etap: Hydrabrazja wodorowa, II etap: Infuzja wodorowa'],
  ['normal',
    'ZJAWISKOWO oferuje ten zabieg w wersji rozszerzonej o infuzję wodorową. Podstawą zabiegu jest aktywny wodór wytwarzany dzięki zastosowaniu wysokiej jakości generatora. Urządzenie usuwa z wody tlen oraz niekorzystne jony chloru, siarki, fosforu i nasyca ją aktywnym wodorem oraz korzystnymi jonami wapnia, magnezu i potasu. Aplikacja tych dobroczynnych substancji następuje w dwóch etapach, jako zasysanie oraz pod ciśnieniem. W ten sposób uzyskujemy także efekt peelingu zewnętrznych warstw naskórka. Aktywny wodór jest najsilniejszym ze znanych antyoksydantów. Jako najmniejszy i najlżejszy z pierwiastków z łatwością wnika w głąb struktur skóry, gdzie wiąże się z najbardziej szkodliwymi wolnymi rodnikami tlenowymi. Skutecznie je neutralizuje, pozbawiając szkodliwych dla skóry właściwości. Następnie w postaci wody jest wydalany z organizmu. Silne właściwości antyoksydacyjne jonów wodoru sprawiają, że nie ma on sobie równych w walce z rodnikowym starzeniem skóry oraz zmianami trądzikowymi. Niemal dosłownie „wymiata” z niej wolne rodniki. Spowalnia, a nawet hamuje w ten sposób procesy starzenia już na poziomie komórkowym, a skóra trądzikowa zaczyna się naturalnie oczyszczać.'],
  ['normal',
    'Oczyszczanie wodorowe nadaje skórze promienny i zdrowy wygląd. Co więcej, aktywny wodór posiada właściwości przeciwzapalne. Oczyszczanie wodorowe można łączyć z wszystkimi zabiegami. Zaleca się rozszerzenie procedury zabiegowej o szyję i dekolt.'],
  ['normal',
    'Największe korzyści przynosi seria co najmniej 5 zabiegów w odstępach co 2-3 tygodnie. Profilaktyka przeciwstarzeniowa i przeciwtrądzikowa to co najmniej 1 zabieg raz w miesiącu. W walce z nasilonym trądzikiem lub zmarszczkami warto wykonać kilka zabiegów w krótszych odstępach czasu, w zależności od potrzeb skóry.'],
  ['normal',
    'Efekty zabiegowe', { marks: ['strong'] }],
  ['normal',
    'świeża, promienna skóra', { listItem: 'bullet' }],
  ['normal',
    'złuszczenie martwych komórek naskórka', { listItem: 'bullet' }],
  ['normal',
    'oczyszczanie porów skóry', { listItem: 'bullet' }],
  ['normal',
    'wygładzenie zmarszczek', { listItem: 'bullet' }],
  ['normal',
    'nawilżenie skóry', { listItem: 'bullet' }],
  ['normal',
    'redukcja zmian trądzikowych', { listItem: 'bullet' }],
  ['normal',
    'spowolnienie procesów starzenia skóry', { listItem: 'bullet' }],
  ['normal',
    'poprawa jędrności szyi i dekoltu', { listItem: 'bullet' }],
  ['normal',
    'Wskazania', { marks: ['strong'] }],
  ['normal',
    'oznaki przedwczesnego starzenia się', { listItem: 'bullet' }],
  ['normal',
    'skóra wymagająca wygładzenia i odświeżenia', { listItem: 'bullet' }],
  ['normal',
    'skóra pozbawiona blasku', { listItem: 'bullet' }],
  ['normal',
    'zmarszczki', { listItem: 'bullet' }],
  ['normal',
    'utrata jędrności skóry', { listItem: 'bullet' }],
  ['normal',
    'zabieg pielęgnacyjny dla każdego rodzaju cery, szczególnie dla skór zanieczyszczonych, ziemistych, pozbawionych blasku, eksponowanych na działanie zanieczyszczeń powietrza, dla osób przebywających w zamkniętych, klimatyzowanych pomieszczeniach', { listItem: 'bullet' }],
  ['normal',
    'cera naczyniowa', { listItem: 'bullet' }],
  ['normal',
    'nadprodukcja serum', { listItem: 'bullet' }],
  ['normal',
    'rozszerzone pory', { listItem: 'bullet' }],
  ['normal',
    'trądzik, zaskórniki', { listItem: 'bullet' }],
  ['normal',
    'opuchlizna, cienie pod oczami', { listItem: 'bullet' }],
  ['normal',
    'skóra bardzo wrażliwa, ze skłonnościami do stanów zapalnych', { listItem: 'bullet' }],
  ['normal',
    'zmarszczki na szyi i dekolcie', { listItem: 'bullet' }],
  ['h3',
    'Peeling kawitacyjny z terapią LED'],
  ['normal',
    'Peeling kawitacyjny to zabieg wykonywany za pomocą ultradźwięków. Kawitacja jest nowoczesną technologią wykorzystywaną głównie do bezbolesnego oczyszczania twarzy. Ultradźwięki o określonej częstotliwości drgań indukują falę kawitacyjną. Fala ta w obecności wody rozprowadzonej na powierzchni skóry tworzy mikroskopijne pęcherzyki wypełnione rozrzedzonym gazem. Pod wpływem drgań ultradźwiękowych pęcherzyki ulegają znacznemu poszerzeniu, a następnie gwałtownie pękają. W krótkim czasie na niewielkiej przestrzeni uwalnia się duża ilość ciepła i znacznie rośnie ciśnienie. To powoduje rozbijanie martwych komórek warstwy rogowej skóry, bez jakichkolwiek uszkodzeń komórek znajdujących się w głębszych warstwach. Peeling kawitacyjny polega na złuszczeniu warstwy rogowej naskórka, łoju, zanieczyszczeń, dając tym samym gładkość, blask skórze oraz lepsze wchłanianie substancji aktywnie czynnych. Połączenie peelingu kawitacyjnego z niebieskim światłem LED daje rezultat wyciszenia skóry, działa antybakteryjnie i przeciwzapalnie. Peelingiem można oczyszczać także szyję i dekolt.'],
  ['normal',
    'Oczyszczanie peelingiem kawitacyjnym zaleca się przeprowadzać raz w miesiącu w serii 5 zabiegów dla zachowania prawidłowego oczyszczania skóry i w celu lepszego wchłaniania kremów, masek lub w zależności od potrzeb skóry.'],
  ['h3',
    'Mikrodermabrazja diamentowa'],
  ['normal',
    'Mikrodermabrazja diamentowa należy do zabiegów mechanicznego ścierania naskórka, dzięki czemu zostaje wzmożona produkcja kolagenu i elastyny. Metoda ta znalazła szerokie zastosowanie do odmładzania skóry, korekcji zmarszczek i blizn, eliminacji plam przebarwieniowych, oczyszczania skóry. Dzięki umiarkowanemu usuwaniu górnych warstw naskórka w jego warstwie podstawnej dochodzi do zintensyfikowanego tworzenia się nowych, pełnowartościowych komórek, które wędrują do góry, zastępując komórki uszkodzone. Złuszczenie warstwy rogowej naskórka zapewnia dużo wyższą absorpcję skóry. Zwiększa się wchłanianie aplikowanych preparatów, następuje wyeliminowanie toksyn i odtrucie głębszych warstw skóry, obserwuje się silne dotlenienie i poprawę mikrokrążenia. Szyja i dekolt także świetnie reagują na mechaniczne ścieranie naskórka.'],
  ['normal',
    'W kuracji przeciwtrądzikowej i przeciwprzebarwieniowej zaleca się przeprowadzenie zabiegów co 2-3 tygodnie, w cyklu 3-6 powtórzeń. W terapii odmładzającej seria obejmuje około 5 zabiegów, w odstępach co 3-4 tygodnie.'],
  ['normal',
    'Wskazania', { marks: ['strong'] }],
  ['normal',
    'trądzik pospolity (zaskórnikowy, grudkowy)', { listItem: 'bullet' }],
  ['normal',
    'blizny potrądzikowe', { listItem: 'bullet' }],
  ['normal',
    'łojotok', { listItem: 'bullet' }],
  ['normal',
    'suchość skóry', { listItem: 'bullet' }],
  ['normal',
    'zaskórniki, prosaki', { listItem: 'bullet' }],
  ['normal',
    'rogowacenie przymieszkowe', { listItem: 'bullet' }],
  ['normal',
    'rozszerzone pory', { listItem: 'bullet' }],
  ['normal',
    'blizny zanikowe i przerosłe', { listItem: 'bullet' }],
  ['normal',
    'przebarwienia i odbarwienia', { listItem: 'bullet' }],
  ['normal',
    'uszkodzenia posłoneczne skóry', { listItem: 'bullet' }],
  ['normal',
    'szorstki, zrogowaciały naskórek', { listItem: 'bullet' }],
  ['normal',
    'zmarszczki wokół oczu, ust', { listItem: 'bullet' }],
  ['normal',
    'wiotkość skóry', { listItem: 'bullet' }],
  ['normal',
    'konieczność starcia naskórka na szyi i dekolcie', { listItem: 'bullet' }],
  ['normal',
    'Wpływ mikrodermabrazji na skórę', { marks: ['strong'] }],
  ['normal',
    'poprawa jakości skóry (struktury i kolorytu)', { listItem: 'bullet' }],
  ['normal',
    'zwiększenie elastyczności', { listItem: 'bullet' }],
  ['normal',
    'zmniejszenie rozszerzonych porów', { listItem: 'bullet' }],
  ['normal',
    'spłycenie powierzchownych zmarszczek, wygładzenie skóry', { listItem: 'bullet' }],
  ['normal',
    'redukcja przebarwień posłonecznych', { listItem: 'bullet' }],
  ['normal',
    'zmniejszenie łojotoku', { listItem: 'bullet' }],
  ['normal',
    'skóra świeższa i młodsza', { listItem: 'bullet' }],
  ['normal',
    'zadbana szyja i dekolt', { listItem: 'bullet' }],
  ['normal',
    'Zalety', { marks: ['strong'] }],
  ['normal',
    'bezpieczna, kontrolowana głębokość ścierania', { listItem: 'bullet' }],
  ['normal',
    'zabieg jest właściwie bezbolesny', { listItem: 'bullet' }],
  ['normal',
    'brak krwawienia i urazu skóry', { listItem: 'bullet' }],
  ['normal',
    'brak długiego okresu gojenia', { listItem: 'bullet' }],
  ['normal',
    'alternatywa dla osób nietolerujących peelingu chemicznego', { listItem: 'bullet' }],
  ['h3',
    'Oczyszczanie manualne'],
  ['normal',
    'Oczyszczanie manualne polega na ręcznym usuwaniu wągrów, zaskórników i grudek niezapalnych. Po zabiegu skóra jest wyraźnie czysta, odświeżona i lepiej przyjmuje substancje aktywne zawarte w kosmetykach. Bardzo ważnym czynnikiem zmniejszającym tworzenie się zanieczyszczeń jest odpowiednio dobrana codzienna pielęgnacja domowa.'],
  ['normal',
    'Przy skórze skłonnej do niedoskonałości zaleca się oczyszczanie skóry według potrzeb.'],
  ['normal',
    'Wskazania', { marks: ['strong'] }],
  ['normal',
    'trądzik pospolity', { listItem: 'bullet' }],
  ['normal',
    'zmiany łojotokowe skóry', { listItem: 'bullet' }],
  ['normal',
    'cera tłusta i mieszana', { listItem: 'bullet' }],
  ['normal',
    'Podczas oczyszczania manualnego można wykorzystać wapozon z ciepłą parą i ozonem.'],
  ['normal',
    'Efekty stosowania wapozonu', { marks: ['strong'] }],
  ['normal',
    'dezynfekcja skóry', { listItem: 'bullet' }],
  ['normal',
    'zmiękczenie skóry', { listItem: 'bullet' }],
  ['normal',
    'otwieranie i czyszczenie porów', { listItem: 'bullet' }],
  ['normal',
    'wydzielanie toksyn przez skórę', { listItem: 'bullet' }],
  ['normal',
    'przyspieszenie cyrkulacji krwi', { listItem: 'bullet' }],
  ['normal',
    'nawilżenie', { listItem: 'bullet' }],
  ['normal',
    'poprawa metabolizmu', { listItem: 'bullet' }],
  ['h3',
    'Mezoterapia bezigłowa'],
  ['normal',
    'Zabieg jest alternatywą dla zabiegów tradycyjnej mezoterapii igłowej. Umożliwia głębokie wprowadzenie substancji odżywczych (fala elektromagnetyczna plus ultradźwięki) bez naruszenia ciągłości naskórka i bez użycia igieł. Dochodzi do zjawiska elektroporacji. Następuje lepsza przepuszczalność błon komórkowych, detoks oraz dotlenienie komórek i przygotowanie na przyjęcie preparatu. Kolejno odbywa się transport cząsteczek preparatu w głąb skóry. Zakończeniem procesu jest zamknięcie się mikrokanałów w błonie komórkowej i tym samym pozostawienie aplikowanych składników w głębszych warstwach tkanki. Ważne, aby zadbać także o szyję i dekolt.'],
  ['normal',
    'Najlepsze efekty przynosi seria 5-10 lub więcej zabiegów co 2 tygodnie przy cerach bardziej wymagających lub seria 3 zabiegów co 2 tygodnie, dla uzyskania efektu odmłodzenia, odżywienia skóry. W profilaktyce warto korzystać z zabiegu raz w miesiącu.'],
  ['normal',
    'Cele zabiegu', { marks: ['strong'] }],
  ['normal',
    'zapobieganie procesom starzenia się skóry (zmarszczki, zwiotczenie mięśni, ścieńczenie się skóry)', { listItem: 'bullet' }],
  ['normal',
    'zwiększenie odporności skóry, polepszenie ukrwienia, odżywienie i pobudzenie metabolizmu tkankowego', { listItem: 'bullet' }],
  ['normal',
    'zmniejszanie przebarwień', { listItem: 'bullet' }],
  ['normal',
    'trądzik pospolity (normalizacja wydzielania sebum, poprawa ukrwienia, nawilżenie skóry)', { listItem: 'bullet' }],
  ['normal',
    'trądzik różowaty, tylko profilaktycznie (w fazie zaostrzonej z wykwitami grudkowo-krostkowymi większość zabiegów kosmetycznych jest przeciwwskazaniem, tylko po konsultacji z lekarzem)', { listItem: 'bullet' }],
  ['normal',
    'redukcja poszerzonych naczyń krwionośnych, wyciszanie rumienia, odnowa płaszcza hydrolipidowego', { listItem: 'bullet' }],
  ['normal',
    'skóra twarzy (nawilżenie, ujędrnienie, pobudzenie produkcji kolagenu i elastyny, stymulacja metabolizmu komórek skóry)', { listItem: 'bullet' }],
  ['normal',
    'dotlenienie dla cer zatrutych nikotyną', { listItem: 'bullet' }],
  ['normal',
    'ulga dla cery zniszczonej nadmierną ekspozycją na słońce i solarium', { listItem: 'bullet' }],
  ['normal',
    'pobudzanie krążenia', { listItem: 'bullet' }],
  ['normal',
    'poprawa jędrności szyi i dekoltu', { listItem: 'bullet' }],
  ['normal',
    'Wskazania', { marks: ['strong'] }],
  ['normal',
    'profilaktyka przeciwzmarszczkowa', { listItem: 'bullet' }],
  ['normal',
    'zwiotczenie skóry', { listItem: 'bullet' }],
  ['normal',
    'brak jędrności skóry', { listItem: 'bullet' }],
  ['normal',
    'cera przesuszona', { listItem: 'bullet' }],
  ['normal',
    'szary koloryt skóry', { listItem: 'bullet' }],
  ['normal',
    'cienie i opuchlizna pod oczami', { listItem: 'bullet' }],
  ['normal',
    'zmarszczki na szyi i dekolcie', { listItem: 'bullet' }],
  ['h3',
    'Radiofrekwencja (fale radiowe)'],
  ['normal',
    'Określana jako niechirurgiczny lifting lub lifting bez skalpela. Fale radiowe stymulują tkanki powierzchowne i te głębiej położone, poprawiają ich dotlenienie, odżywienie oraz mikrocyrkulację. Zabieg polega na przegrzewaniu włókien kolagenowych, co wywołuje ich skurczenie i napinanie, dzięki czemu następuje proces regeneracji. Ponadto fale radiowe stymulują fibroblasty do odbudowy i wytwarzania kolagenu oraz elastyny, dając efekt zmniejszenia widoczności zmarszczek. Zwiększa się gęstość, elastyczność i napięcie skóry, poprawia się owal i koloryt twarzy. W wielu przypadkach już po wykonaniu pierwszego zabiegu można zauważyć różnicę w wyglądzie skóry. Efekt dogłębnej poprawy może pojawić się po serii zabiegów. Zabieg ten przyczynia się do minimalizacji zmarszczek. Warto dodać do zabiegu pielęgnację szyi i dekoltu.'],
  ['normal',
    'Fale radiowe zaleca się zacząć stosować już po 25 roku życia, raz na 2-3 miesiące. Po 35 roku życia powinno się je wykonywać raz w miesiącu. Po 45 roku życia zaleca się serię 5-10 zabiegów co 2 tygodnie. Profilaktyka przeciw starzeniu to 1 zabieg w miesiącu.'],
  ['normal',
    'Efekty zabiegowe', { marks: ['strong'] }],
  ['normal',
    'obkurczenie zwisającego podbródka', { listItem: 'bullet' }],
  ['normal',
    'uniesienie opadających górnych powiek', { listItem: 'bullet' }],
  ['normal',
    'poprawa krążenia krwi', { listItem: 'bullet' }],
  ['normal',
    'poprawa napięcia policzków', { listItem: 'bullet' }],
  ['normal',
    'napięcie zwiotczeń', { listItem: 'bullet' }],
  ['normal',
    'poprawa owalu twarzy, tak zwanych „chomików”', { listItem: 'bullet' }],
  ['normal',
    'spłycenie głębokich zmarszczek', { listItem: 'bullet' }],
  ['normal',
    'zmniejszenie „worków” pod oczami i „kurzych łapek”', { listItem: 'bullet' }],
  ['normal',
    'odbudowa kolagenu', { listItem: 'bullet' }],
  ['normal',
    'terapia zapobiegająca starzeniu, profilaktyka', { listItem: 'bullet' }],
  ['normal',
    'zmniejszenie przebarwień', { listItem: 'bullet' }],
  ['normal',
    'redukcja rozszerzonych porów', { listItem: 'bullet' }],
  ['normal',
    'poprawa jędrności szyi i dekoltu', { listItem: 'bullet' }],
  ['normal',
    'Wskazania', { marks: ['strong'] }],
  ['normal',
    'lifting okolic oczu', { listItem: 'bullet' }],
  ['normal',
    'lifting twarzy', { listItem: 'bullet' }],
  ['normal',
    'lifting szyi i dekoltu', { listItem: 'bullet' }],
  ['normal',
    'poprawa kondycji zwiotczałej skóry', { listItem: 'bullet' }],
  ['normal',
    'zmniejszanie widocznych zmarszczek na czole', { listItem: 'bullet' }],
  ['normal',
    'zmarszczki na szyi i dekolcie', { listItem: 'bullet' }],
  ['h3',
    'Ultradźwięki i sonoforeza'],
  ['normal',
    'Fale ultradźwiękowe o niskiej częstotliwości przenikają przez warstwę ochronną naskórka, dzięki wykorzystaniu czerwonego światła LED transportują głębiej składniki odżywcze oraz powodują mikromasaż skóry, zostaje wzmożona produkcja kolagenu i elastyny, których brak jest jednym z podstawowych czynników starzenia się skóry. Terapia ultradźwiękami jest łagodna i nieinwazyjna. Za pomocą ultradźwięków można zadziałać na potrzeby każdego typu cery. Zabieg zaleca się także rozszerzyć o szyję i dekolt.'],
  ['normal',
    'Sonoforeza w zabiegu to także wykorzystanie ultradźwięków.'],
  ['normal',
    'Przy ultradźwiękach wskazane jest przeprowadzenie serii 5 zabiegów co 2 tygodnie, w celu wtłoczenia składników odżywczych w głąb skóry, dla przedłużenia działania zabiegów.'],
  ['normal',
    'Efekty zabiegowe', { marks: ['strong'] }],
  ['normal',
    'dotlenienie i głębokie nawilżenie skóry', { listItem: 'bullet' }],
  ['normal',
    'rozjaśnienie przebarwień i plam', { listItem: 'bullet' }],
  ['normal',
    'stymulacja syntezy kolagenu, elastyny, kwasu hialuronowego', { listItem: 'bullet' }],
  ['normal',
    'zwiększenie penetracji kosmetyków', { listItem: 'bullet' }],
  ['normal',
    'poprawa gęstości skóry', { listItem: 'bullet' }],
  ['normal',
    'powstrzymanie powstawania przebarwień i plam', { listItem: 'bullet' }],
  ['normal',
    'uszczelnienie i obkurczenie naczyń krwionośnych', { listItem: 'bullet' }],
  ['normal',
    'dzięki efektowi cieplnemu zwiększa się poziom metabolizmu komórkowego i przyswajania przez komórki substancji odżywczych, przyspiesza się proces odnowy i regeneracji skóry oraz eliminacji zmarszczek', { listItem: 'bullet' }],
  ['normal',
    'możliwość bezinwazyjnego wprowadzania w głąb skóry substancji leczniczych i pielęgnacyjnych', { listItem: 'bullet' }],
  ['normal',
    'Każdy zabieg może być wykonywany przez cały rok, pod warunkiem zachowania odpowiednich procedur pozabiegowych. Długotrwałe efekty uzyskuje się po przeprowadzeniu serii. Można poszerzać obszar zabiegu o pielęgnację szyi i dekoltu. Zabiegi rozpoczynam peelingiem i kończę maską.'],
  ['h3',
    'Przeciwwskazania'],
  ['normal',
    'Zależą od konkretnego zabiegu, ale najczęściej powtarzają się: ciąża i karmienie piersią, aktywne infekcje i stany zapalne skóry, przerwanie ciągłości naskórka, choroby nowotworowe, padaczka, rozrusznik serca i implanty elektroniczne, metalowe elementy w polu zabiegowym, świeża opalenizna oraz przyjmowanie preparatów uwrażliwiających na światło. Lista ma charakter orientacyjny, a o kwalifikacji do konkretnego zabiegu decydujemy wspólnie podczas konsultacji.'],
])

export const treatments = [
  {
    title: 'Depilacja laserowa',
    kicker: 'Depilacja laserowa',
    navLabel: 'Depilacja laserowa',
    slug: 'depilacja-laserowa',
    excerpt:
      'Trwała redukcja owłosienia w serii około ośmiu zabiegów. Laser na miejscu w Krzeszowicach, dostępny każdego dnia pracy salonu, więc terminy ustalam pod Twój kalendarz.',
    featured: true,
    ctaLabel: 'Umów wizytę',
    pricelistAnchor: 'depilacja-laserowa',
    order: 0,
    atuty: [
      'Wskaźnik satysfakcji 100%',
      'Laser na miejscu w Krzeszowicach, dostępny każdego dnia pracy salonu',
      'Kolejne zabiegi serii w dogodnym terminie, bez przerw wymuszonych dostępnością sprzętu',
      'Pełna seria to zwykle około ośmiu zabiegów, w odstępach zazwyczaj pięciu tygodni',
      'Bezpłatna konsultacja i próba laserowa w razie potrzeby',
      'Pakiety obejmujące kilka partii, z ceną niższą niż suma pojedynczych zabiegów',
      'Zapomnij o maszynce i wosku między wizytami: między zabiegami wolno golić',
      'Depilacja bez żelu',
      'Mała głowica chłodząca',
      'Duża głowica próżniowa',
      'Dodatkowe chłodzenie wrażliwych obszarów',
    ],
    description: laserDescription,
  },
  {
    title: 'Pielęgnacja twarzy',
    kicker: 'Pielęgnacja twarzy',
    navLabel: 'Pielęgnacja twarzy',
    slug: 'pielegnacja-twarzy',
    excerpt:
      'Oczyszczanie wodorowe, peeling kawitacyjny, mikrodermabrazja diamentowa, oczyszczanie manualne, mezoterapia bezigłowa, radiofrekwencja, ultradźwięki i sonoforeza. Protokół układam pod bieżący stan skóry.',
    featured: true,
    ctaLabel: 'Umów wizytę',
    pricelistAnchor: 'pielegnacja-twarzy',
    order: 1,
    atuty: [
      'Kompleksowa pielęgnacja i rewitalizacja',
      'Efekt ujędrnienia i odmłodzenia',
      'Bezpłatna konsultacja i ocena skóry przed każdym zabiegiem',
      'Protokół dobierany pod bieżący stan cery, nie pod nazwę usługi z cennika',
      'Zabiegi oczyszczające, złuszczające, nawilżające i ujędrniające',
      'Rabat na serię pięciu zabiegów oraz na dwa różne zabiegi podczas jednej wizyty',
      'Dobór pielęgnacji domowej, żeby efekt wizyty utrzymał się dłużej',
      'Nowoczesne technologie',
      'Bezpłatna konsultacja podczas zabiegu',
    ],
    description: twarzDescription,
  },
]

/* ── Cennik ──────────────────────────────────────────────────────────── */

export const pricelist = {
  intro:
    'Ceny obejmują pojedynczy zabieg. Zakres i koszt ustalamy ostatecznie podczas konsultacji, po ocenie skóry i rozmowie o Twoich potrzebach.',
  outro:
    'Cennik ma charakter informacyjny i nie stanowi oferty w rozumieniu przepisów prawa. Aktualne ceny potwierdzam przy zapisie na wizytę.',
  groups: [
    {
      title: 'Depilacja laserowa',
      anchor: 'depilacja-laserowa',
      showInMenu: true,
      note: 'Cena dotyczy jednego zabiegu na wskazanym obszarze. Pełna seria to zwykle około ośmiu zabiegów.',
      items: [
        { name: 'Łydki, stopy i palce', price: '250 zł' },
        { name: 'Uda i kolana', price: '300 zł' },
        { name: 'Całe nogi', price: '450 zł' },
        { name: 'Bikini płytkie', price: '200 zł' },
        { name: 'Bikini średnie', price: '250 zł' },
        { name: 'Bikini głębokie', price: '300 zł' },
        { name: 'Okolice bikini', price: '150 zł' },
        { name: 'Przestrzeń międzypośladkowa', price: '100 zł' },
        { name: 'Pośladki', price: '200 zł' },
        { name: 'Linia biała', price: '100 zł' },
        { name: 'Pachy', price: '150 zł' },
        { name: 'Wąsik', price: '100 zł' },
        { name: 'Broda', price: '150 zł' },
        { name: 'Twarz: baki i policzki', price: '200 zł' },
        { name: 'Kark', price: '150 zł' },
        { name: 'Plecy', price: '350 zł' },
        { name: 'Ramiona', price: '200 zł' },
        { name: 'Przedramiona', price: '200 zł' },
        { name: 'Dłonie i palce', price: '100 zł' },
        { name: 'Całe ręce', price: '350 zł' },
        { name: 'Klatka piersiowa', price: '250 zł' },
        { name: 'Brzuch', price: '200 zł' },
      ],
    },
    {
      title: 'Pakiety depilacji laserowej',
      anchor: 'pakiety-depilacji',
      showInMenu: false,
      note: 'Można wybrać jeden pakiet. Podana cena dotyczy jednej wizyty, a oszczędność policzona jest dla serii ośmiu zabiegów.',
      items: [
        { name: 'Łydki i bikini płytkie', price: '450 zł', oldPrice: '600 zł', saving: '1200 zł', gratis: 'pachy gratis' },
        { name: 'Łydki i bikini średnie', price: '500 zł', oldPrice: '650 zł', saving: '1200 zł', gratis: 'pachy gratis' },
        { name: 'Łydki i bikini głębokie', price: '550 zł', oldPrice: '700 zł', saving: '1200 zł', gratis: 'pachy gratis' },
        { name: 'Pośladki i przestrzeń międzypośladkowa', price: '250 zł', oldPrice: '300 zł', saving: '400 zł' },
        { name: 'Pachy: 6 zabiegów', price: '150 zł', saving: '300 zł', gratis: '2 zabiegi gratis' },
        { name: 'Plecy', price: '350 zł', oldPrice: '500 zł', saving: '1200 zł', gratis: 'kark gratis' },
        { name: 'Plecy i kark', price: '500 zł', oldPrice: '650 zł', saving: '1200 zł', gratis: 'pachy gratis' },
        { name: 'Klatka piersiowa i brzuch', price: '350 zł', oldPrice: '450 zł', saving: '800 zł' },
        { name: 'Wąsik i broda', price: '200 zł', oldPrice: '250 zł', saving: '400 zł' },
        { name: 'Broda i twarz', price: '350 zł', oldPrice: '450 zł', saving: '800 zł', gratis: 'wąsik gratis' },
        { name: 'Pakiet na start: całe nogi i pachy', price: '500 zł', oldPrice: '600 zł' },
      ],
    },
    {
      title: 'Pielęgnacja twarzy',
      anchor: 'pielegnacja-twarzy',
      noteAfter: 'Gratis maska i peeling przy każdym zabiegu.',
      showInMenu: true,
      note: 'Rabat 20% na serię pięciu zabiegów albo szósty zabieg gratis. Rabat 20% przy dwóch różnych zabiegach wykonanych podczas jednej wizyty.',
      items: [
        { name: 'Oczyszczanie wodorowe PREMIUM, twarz', price: '240 zł', note: '90 min' },
        { name: 'Oczyszczanie wodorowe PREMIUM, twarz, szyja i dekolt', price: '290 zł', note: '120 min' },
        { name: 'Peeling kawitacyjny z terapią LED, twarz', price: '140 zł', note: '45 min' },
        { name: 'Peeling kawitacyjny z terapią LED, twarz, szyja i dekolt', price: '170 zł', note: '60 min' },
        { name: 'Mikrodermabrazja diamentowa, twarz', price: '190 zł', note: '60 min' },
        { name: 'Mikrodermabrazja diamentowa, twarz, szyja i dekolt', price: '230 zł', note: '90 min' },
        { name: 'Oczyszczanie manualne', price: '250 zł', note: '120 – 180 min' },
        { name: 'Usuwanie prosaków', price: '30 – 50 zł' },
        { name: 'Mezoterapia bezigłowa REVITAL 20+ i 30+, twarz', price: '280 zł', note: '70 min' },
        { name: 'Mezoterapia bezigłowa REVITAL 20+ i 30+, twarz, szyja i dekolt', price: '320 zł', note: '90 min' },
        { name: 'Mezoterapia bezigłowa, ODMŁADZANIE 40+, twarz', price: '280 zł', note: '70 min' },
        { name: 'Mezoterapia bezigłowa, ODMŁADZANIE 40+, twarz, szyja i dekolt', price: '320 zł', note: '90 min' },
        { name: 'Mezoterapia bezigłowa, LIFTING 45+, twarz', price: '280 zł', note: '70 min' },
        { name: 'Mezoterapia bezigłowa, LIFTING 45+, twarz, szyja i dekolt', price: '320 zł', note: '90 min' },
        { name: 'Mezoterapia bezigłowa, NACZYNKA twarz', price: '280 zł', note: '70 min' },
        { name: 'Mezoterapia bezigłowa, TRĄDZIK twarz', price: '280 zł', note: '70 min' },
        { name: 'Radiofrekwencja, LIFTING okolic oka', price: '120 zł', note: '40 min' },
        { name: 'Radiofrekwencja, LIFTING twarzy', price: '160 zł', note: '60 min' },
        { name: 'Radiofrekwencja, cała twarz', price: '250 zł', note: '70 min' },
        { name: 'Radiofrekwencja, cała twarz, szyja i dekolt', price: '290 zł', note: '90 min' },
        { name: 'Ultradźwięki, twarz', price: '210 zł', note: '70 min' },
        { name: 'Ultradźwięki, twarz, szyja i dekolt', price: '240 zł', note: '90 min' },
        { name: 'Sonoforeza, twarz', price: '150 zł', note: '70 min' },
        { name: 'Sonoforeza, twarz, szyja i dekolt', price: '180 zł', note: '90 min' },
        { name: 'Regulacja brwi', price: '30 zł', note: '20 min' },
        { name: 'Koloryzacja rzęs', price: '40 zł', note: '30 min' },
        { name: 'Koloryzacja brwi z peelingiem i regulacją', price: '70 zł', note: '40 min' },
        { name: 'Koloryzacja brwi i rzęs z peelingiem i regulacją brwi', price: '100 zł', note: '60 min' },
      ],
    },
    {
      title: 'Dodatki do zabiegów',
      anchor: 'dodatki',
      showInMenu: false,
      items: [
        { name: 'Ampułka', price: '30 zł' },
        { name: 'Maska algowa', price: '20 zł' },
      ],
    },
  ],
}

/* ── FAQ ─────────────────────────────────────────────────────────────── */

export const faqs = [
  {
    question: 'Kiedy należy rozpocząć serię depilacji laserowej?',
    answer:
      'Bardzo ważne, aby serię rozpocząć wczesną jesienią, żeby całą zdążyć wykonać do maja. Jeśli rozpoczniesz serię później, oczywiście jest to możliwe w każdym czasie, ale latem będzie trzeba zrobić przerwę ze względu na mocne promieniowanie słoneczne i dokończyć ją kolejnej jesieni, a wtedy do serii trzeba dołożyć jeden lub dwa zabiegi. Dlatego pamiętaj, aby nie przegapić odpowiedniego momentu.',
  },
  {
    question: 'Ile zabiegów depilacji laserowej potrzeba?',
    answer:
      'U większości osób pełna seria to około ośmiu zabiegów. Laser działa skutecznie tylko na włosy w fazie aktywnego wzrostu, a w danym momencie jest w niej jedynie część owłosienia, więc kolejne wizyty obejmują te włosy, które w międzyczasie weszły w tę fazę. Ostateczną liczbę ustalamy po konsultacji, bo zależy od partii ciała, koloru i grubości włosa oraz uwarunkowań hormonalnych.',
  },
  {
    question: 'Co ile tygodni umawiamy kolejne zabiegi depilacji?',
    answer:
      'Odstęp pomiędzy kolejnymi zabiegami wynosi zazwyczaj pięć tygodni. Zbyt krótka przerwa oznacza pracę na włosach poza fazą wzrostu, zbyt długa pozwala części mieszków przejść pełny cykl. Laser mam na miejscu i jest dostępny każdego dnia pracy salonu, więc termin dopasowuję do Twojego kalendarza, a nie do dostępności sprzętu.',
  },
  {
    question: 'Jak przygotować się do depilacji laserowej?',
    answer:
      'Obszar zabiegu wygol maszynką na 12 do 24 godzin przed wizytą. Na co najmniej cztery tygodnie wcześniej odstaw wosk, pastę cukrową, depilator i pęsetę, bo laser potrzebuje włosa w mieszku. Na dwa do czterech tygodni przed zabiegiem zrezygnuj z opalania i solarium, a samoopalacz zmyj całkowicie. Kwasy i retinol warto odstawić około miesiąca wcześniej. Na zabieg przyjdź ze skórą czystą, bez balsamu i dezodorantu.',
  },
  {
    question: 'Czy zabieg depilacji boli?',
    answer:
      'W trakcie odczuwa się zwykle ciepło i delikatne ukłucia, wyraźniej w partiach wrażliwych, takich jak bikini czy twarz, oraz przy grubym, ciemnym włosie. Po zabiegu skóra bywa zaczerwieniona i rozgrzana. U większości osób ta reakcja ustępuje w ciągu jednego do trzech dni, choć wrażliwość jest sprawą indywidualną.',
  },
  {
    question: 'Jakie są przeciwwskazania do depilacji?',
    answer:
      'Do najczęstszych należą ciąża i karmienie piersią, świeża opalenizna oraz samoopalacz na skórze, aktywne infekcje i zmiany skórne w miejscu zabiegu, przyjmowanie retinoidów i leków fotouczulających, padaczka, rozrusznik serca i choroby nowotworowe. Ta lista ma charakter orientacyjny. Przed pierwszą wizytą przeprowadzam wywiad, a część stanów zdrowia wymaga wcześniejszej konsultacji lekarskiej. Nigdy nie odstawiaj leków samodzielnie, decyzję podejmuje Twój lekarz.',
  },
  {
    question: 'Jak dbać o skórę po zabiegu depilacji?',
    answer:
      'Przez kilka dni odpuść saunę, gorące kąpiele, basen i intensywny wysiłek. Skórę myj łagodnie i nawilżaj, a odsłonięte partie chroń wysokim filtrem przez cały czas trwania serii, bo to zmniejsza ryzyko przebarwień. Między zabiegami wolno wyłącznie golić. Potraktowane włosy wypadają stopniowo przez kilka do kilkunastu dni, co bywa mylone z odrastaniem.',
  },
  {
    question: 'Który zabieg na twarz wybrać?',
    answer:
      'Nie musisz wybierać przed wizytą. Zaczynamy od rozmowy i oceny skóry, a zabieg dobieram do jej bieżącego stanu. Skóra zanieczyszczona i matowa zwykle korzysta z oczyszczania, skóra odwodniona z zabiegów wprowadzających substancje aktywne, a skóra z obniżoną jędrnością z zabiegów liftingujących, takich jak radiofrekwencja. Większość zabiegów pracuje najlepiej w serii, z zachowaniem odstępów.',
  },
  {
    question: 'Dlaczego warto robić serię zabiegów na twarz?',
    answer:
      'To sposób na widoczną i trwałą poprawę stanu skóry. Jednorazowy zabieg przynosi najczęściej tzw. efekt bankietowy: skóra jest odświeżona i napięta na kilka dni lub tygodni. Natomiast każdy kolejny zabieg z serii, w odstępach dwóch do trzech tygodni, nadbudowuje efekt poprzedniego, głęboko regenerując i zagęszczając tkankę od wewnątrz.',
  },
  {
    question: 'Kiedy oczyszczanie wodorowe przynosi efekty?',
    answer:
      'Tylko wtedy, kiedy urządzenie posiada generator wodoru. To podstawa. Salon ZJAWISKOWO posiada taki sprzęt. Ponadto w moim salonie otrzymujesz ten zabieg w wersji PREMIUM, co oznacza, że oprócz podstawowej wersji zabiegowej dostajesz dodatkowo w gratisie infuzję wodorową, która intensywnie nawilża i liftinguje skórę pod wpływem ciśnienia, wymiatając z niej niekorzystne wolne rodniki.',
  },
  {
    question: 'Czy mogę kupić voucher na zabieg?',
    answer:
      'Tak. Voucher można wykupić na konkretny zabieg albo na wybraną kwotę, którą obdarowana osoba wykorzysta na dowolną usługę z cennika. Szczegóły znajdziesz na stronie z voucherami, a najprościej zapytać telefonicznie.',
  },
]

/* ── O mnie ──────────────────────────────────────────────────────────── */

export const about = {
  kicker: 'Salon',
  heading: 'O mnie',
  lead: 'ZJAWISKOWO prowadzę sama. To znaczy, że konsultację, zabieg i całą serię wykonuje u Ciebie jedna osoba, która pamięta, jak Twoja skóra zachowała się ostatnim razem.',
  atuty: [
    'Salon prowadzę jednoosobowo, bez rotacji personelu',
    'Jedna osoba prowadzi Cię od konsultacji przez całą serię zabiegów',
    'Kameralny gabinet, jedna klientka w danym czasie',
    'Laser i sprzęt do pielęgnacji twarzy na miejscu w Krzeszowicach',
  ],
  body: blocks('about', [
    ['normal',
      'W kameralnym salonie łatwiej o rzeczy, które w większym gabinecie giną. Nie musisz za każdym razem opowiadać historii swojej skóry od początku, bo pamiętam, jak zareagowała poprzednio i co z tego wynikło. Nie ma pośpiechu między jedną klientką a drugą, bo w danym czasie jest tu jedna osoba.'],
    ['h3', 'Jak pracuję'],
    ['normal',
      '[Do uzupełnienia przez Martę: kilka zdań o drodze zawodowej, ukończonych szkoleniach i certyfikatach oraz o tym, od kiedy działa salon. To miejsce, w którym warto napisać konkretnie, bo klientki czytają je uważnie.]'],
    ['h3', 'Podejście do zabiegów'],
    ['normal',
      'Każdą wizytę zaczynam od rozmowy i oceny skóry. Zabieg dobieram do jej bieżącego stanu, a nie do nazwy usługi z cennika, i mówię wprost, kiedy lepiej odczekać albo wybrać coś łagodniejszego. Przy depilacji laserowej pilnuję odstępów w serii, bo to od nich zależy, czy praca ma sens.'],
    ['h3', 'Dlaczego Krzeszowice'],
    ['normal',
      '[Do uzupełnienia przez Martę: dlaczego salon powstał tutaj, co daje klientkom to, że nie muszą jeździć do Krakowa.]'],
  ]),
}

export const aboutBody =
  '[Opis do uzupełnienia: droga zawodowa, ukończone szkolenia, od kiedy działa salon, podejście do klientek.]'

/* ── Vouchery ────────────────────────────────────────────────────────── */

export const voucher = {
  kicker: 'Prezent',
  heading: 'Vouchery podarunkowe',
  lead: 'Voucher do ZJAWISKOWO to prezent, który obdarowana osoba wykorzysta wtedy, kiedy będzie miała na to czas i ochotę. Można go wykupić na konkretny zabieg albo na wybraną kwotę.',
  bullets: [
    'Voucher na konkretny zabieg albo na dowolnie wybraną kwotę',
    'Do wykorzystania na wszystkie usługi z cennika, także na pakiety depilacji',
    'Termin ważności 12 miesięcy',
    'Do odbioru w salonie w eleganckiej torebce',
    'Rezerwacja terminu telefonicznie',
  ],
  ctaLabel: 'Zapytaj o voucher',
  showOnHome: true,
  body: blocks('voucher', [
    ['normal',
      'Jeżeli nie wiesz, który zabieg wybrać, najprościej podarować kwotę. Obdarowana osoba przyjdzie na konsultację, opowie o swojej skórze i razem dobierzemy to, co będzie miało dla niej sens. Voucher można też wystawić na konkretną usługę, na przykład na oczyszczanie wodorowe albo na pierwszy zabieg z serii depilacji laserowej.'],
    ['h3',
      'Jak kupić'],
    ['normal',
      'Zadzwoń i ustalimy kwotę lub zabieg, a voucher przygotuję do odbioru w salonie. Możliwa jest płatność kartą lub gotówką. Voucher będzie pięknie zapakowany w torebce, w ten sposób oszczędzasz czas i unikasz dodatkowych kosztów zakupu opakowania.'],
    ['h3',
      'Jak wykorzystać'],
    ['normal',
      'Wystarczy zadzwonić i ustalić wizytę. Voucher nie podlega wymianie na gotówkę, nie może z niego skorzystać inna osoba niż obdarowana, a termin 12 miesięcy nie ulega przedłużeniu. Jeśli wartość zabiegu przekracza wartość vouchera, różnicę dopłaca się na miejscu.'],
  ]),
}

/* ── Regulamin ───────────────────────────────────────────────────────── */

export const terms = {
  kicker: 'Informacje prawne',
  heading: 'Regulamin salonu',
  lead: 'Poniższe zasady porządkują przebieg wizyty i rezerwacji. Ich celem jest to, żeby każda klientka miała zarezerwowany dla siebie czas i spokój.',
  notice:
    '[Dokument roboczy, treść przykładowa do uzupełnienia i weryfikacji prawnej przed publikacją.]',
  updatedAt: 'lipiec 2026',
  privacyIntro:
    'Zasady przetwarzania danych osobowych, obsługi formularza kontaktowego oraz korzystania z plików cookies opisuje osobny dokument.',
  body: blocks('terms', [
    ['h3', '1. Postanowienia ogólne'],
    ['normal',
      'Regulamin określa zasady korzystania z usług salonu kosmetycznego ZJAWISKOWO, [pełna nazwa działalności], [adres], NIP [NIP]. Skorzystanie z usług oznacza akceptację niniejszego regulaminu.'],
    ['h3', '2. Rezerwacja wizyty'],
    ['normal',
      'Wizyty rezerwuje się telefonicznie pod numerem [telefon] lub przez formularz kontaktowy. Rezerwacja jest potwierdzana [sposób potwierdzenia]. Prosimy o przybycie kilka minut przed umówioną godziną. Spóźnienie może skrócić zabieg lub wymagać zmiany terminu, ponieważ kolejna wizyta zaczyna się o stałej porze.'],
    ['h3', '3. Odwołanie i zmiana terminu'],
    ['normal',
      'Termin można odwołać lub przełożyć najpóźniej [liczba] godzin przed wizytą. [Do uzupełnienia: konsekwencje późnego odwołania lub niestawienia się, ewentualny zadatek przy dłuższych zabiegach.]'],
    ['h3', '4. Konsultacja i kwalifikacja do zabiegu'],
    ['normal',
      'Przed pierwszym zabiegiem przeprowadzany jest wywiad dotyczący stanu zdrowia, przyjmowanych leków i przeciwwskazań. Klientka zobowiązuje się do udzielenia zgodnych z prawdą informacji. Salon zastrzega sobie prawo do odmowy wykonania zabiegu, jeżeli istnieją przeciwwskazania lub stan skóry na to nie pozwala.'],
    ['h3', '5. Przebieg zabiegu'],
    ['normal',
      'Zabiegi wykonywane są zgodnie z zaleceniami producentów urządzeń i preparatów oraz z wiedzą kosmetologiczną. Klientka zobowiązuje się do stosowania zaleceń przed zabiegiem i po nim. Niestosowanie się do zaleceń może wpłynąć na przebieg i rezultat zabiegu.'],
    ['h3', '6. Płatności'],
    ['normal',
      'Płatność następuje po wykonaniu zabiegu, [dostępne formy płatności]. Ceny podane w cenniku mają charakter informacyjny i nie stanowią oferty w rozumieniu przepisów prawa.'],
    ['h3', '7. Vouchery i pakiety'],
    ['normal',
      'Voucher ważny jest przez [okres] od daty zakupu i nie podlega wymianie na gotówkę. Pakiet zabiegów obejmuje [zakres], a jego wykorzystanie następuje w terminie [okres]. [Do uzupełnienia: zasady przy rezygnacji z rozpoczętego pakietu.]'],
    ['h3', '8. Reklamacje'],
    ['normal',
      'Uwagi dotyczące wykonanej usługi prosimy zgłaszać w terminie [liczba] dni od zabiegu, osobiście, telefonicznie lub na adres [e-mail]. Zgłoszenie rozpatrywane jest w terminie [liczba] dni.'],
    ['h3', '9. Bezpieczeństwo i porządek'],
    ['normal',
      'Na terenie salonu obowiązuje zakaz palenia. Ze względu na charakter zabiegów prosimy o przybycie bez osób towarzyszących. [Do uzupełnienia: zasady dotyczące dzieci, zwierząt, rzeczy wartościowych.]'],
    ['h3', '10. Postanowienia końcowe'],
    ['normal',
      'Salon zastrzega sobie prawo do zmiany regulaminu. Aktualna wersja jest zawsze dostępna na tej stronie oraz do wglądu w salonie. W sprawach nieuregulowanych zastosowanie mają przepisy powszechnie obowiązującego prawa.'],
  ]),
}

/* ── Dlaczego ZJAWISKOWO ─────────────────────────────────────────────── */

export const badges = [
  { text: '100% zadowolonych klientów', order: 1 },
  { text: 'Najwyżej oceniany, największa liczba rekomendacji', order: 2 },
  { text: 'I miejsce w rankingu pozytywnych opinii', order: 3 },
  { text: 'Nominacja do plebiscytu „Mistrzowie Urody”', order: 4 },
  { text: 'Zaufanie budowane efektami', order: 5 },
  { text: 'Bezkompromisowa jakość', order: 6 },
  { text: 'Certyfikowane urządzenia', order: 7 },
  { text: 'Wiedza, która tworzy piękno', order: 8 },
]

/* ── Opinie ──────────────────────────────────────────────────────────────
   Treść przykładowa. Klientka podmienia na własne opinie z wizytówki Google.
   Celowo mówią o atmosferze, obsłudze i komforcie, a nie o efektach zabiegu:
   opinia obiecująca konkretny rezultat byłaby dla salonu ryzykowna prawnie. */

export const reviews = [
  {
    quote: 'Świetna atmosfera i pełen profesjonalizm. Czuję się tu zaopiekowana od progu.',
    author: 'Anna K.',
    rating: 5,
    order: 1,
  },
  {
    quote: 'Dobrze wykonany zabieg i spokojna, rzeczowa rozmowa. Wszystko wytłumaczone krok po kroku.',
    author: 'Magda W.',
    rating: 5,
    order: 2,
  },
  {
    quote: 'Czysto, elegancko i zawsze punktualnie. Doceniam, że nikt się nie spieszy.',
    author: 'Joanna R.',
    rating: 5,
    order: 3,
  },
  {
    quote: 'Terminy dopasowane do mojego grafiku, bez czekania miesiąc na kolejną wizytę.',
    author: 'Ewelina S.',
    rating: 5,
    order: 4,
  },
  {
    quote: 'Miła obsługa i dokładna konsultacja przed zabiegiem. Polecam każdej znajomej.',
    author: 'Karolina P.',
    rating: 5,
    order: 5,
  },
]
