import { defineType, defineField } from 'sanity'

export const siteSettings = defineType({
  name: 'siteSettings',
  title: 'Ustawienia salonu',
  type: 'document',
  groups: [
    { name: 'general', title: 'Ogólne' },
    { name: 'hero', title: 'Sekcja główna (hero)' },
    { name: 'promo', title: 'Pasek promocji' },
    { name: 'contact', title: 'Kontakt' },
  ],
  fields: [
    defineField({
      name: 'salonName',
      title: 'Nazwa salonu',
      type: 'string',
      group: 'general',
      initialValue: 'ZJAWISKOWO',
    }),
    defineField({
      name: 'theme',
      title: 'Wariant kolorystyczny',
      type: 'string',
      group: 'general',
      options: {
        list: [
          { title: 'Złota elegancja', value: 'gold' },
          { title: 'Lawendowy blask', value: 'lavender' },
          { title: 'Świetlista biel', value: 'white' },
        ],
        layout: 'radio',
      },
      initialValue: 'gold',
    }),
    defineField({
      name: 'heroKicker',
      title: 'Nadtytuł',
      type: 'string',
      group: 'hero',
      initialValue: 'Salon kosmetyczny · Krzeszowice',
    }),
    defineField({
      name: 'tagline',
      title: 'Hasło główne',
      type: 'string',
      group: 'hero',
      initialValue: 'Piękno zaczyna się tutaj',
    }),
    defineField({
      name: 'heroLead',
      title: 'Opis pod hasłem',
      type: 'text',
      rows: 2,
      group: 'hero',
    }),
    defineField({
      name: 'heroFaceImage',
      title: 'Zdjęcie — kosmetyka twarzy',
      type: 'image',
      options: { hotspot: true },
      group: 'hero',
    }),
    defineField({
      name: 'heroLaserImage',
      title: 'Zdjęcie — depilacja laserowa',
      type: 'image',
      options: { hotspot: true },
      group: 'hero',
    }),
    defineField({
      name: 'heroMainImage',
      title: 'Zdjęcie główne (wariant „Świetlista biel")',
      type: 'image',
      options: { hotspot: true },
      group: 'hero',
    }),
    defineField({
      name: 'heroSlides',
      title: 'Slajdy hero (wariant „Lawendowy blask")',
      type: 'array',
      of: [{ type: 'image', options: { hotspot: true } }],
      group: 'hero',
    }),
    defineField({
      name: 'showPromo',
      title: 'Pokaż pasek promocji',
      type: 'boolean',
      group: 'promo',
      initialValue: true,
    }),
    defineField({
      name: 'promoText',
      title: 'Treść promocji',
      type: 'string',
      group: 'promo',
    }),
    defineField({
      name: 'phone',
      title: 'Telefon',
      type: 'string',
      group: 'contact',
      initialValue: '517 899 229',
    }),
    defineField({
      name: 'address',
      title: 'Adres',
      type: 'string',
      group: 'contact',
    }),
    defineField({
      name: 'hours',
      title: 'Godziny otwarcia',
      type: 'string',
      group: 'contact',
    }),
    defineField({
      name: 'facebookUrl',
      title: 'Facebook (URL)',
      type: 'url',
      group: 'contact',
    }),
    defineField({
      name: 'instagramUrl',
      title: 'Instagram (URL)',
      type: 'url',
      group: 'contact',
    }),
    defineField({
      name: 'googleMapsEmbedUrl',
      title: 'Mapa Google — adres osadzenia (embed URL)',
      type: 'url',
      group: 'contact',
    }),
    defineField({
      name: 'contactEmail',
      title: 'E-mail kontaktowy (na który idą wiadomości z formularza)',
      type: 'string',
      group: 'contact',
    }),
    defineField({
      name: 'formEndpoint',
      title: 'Formularz — adres Formspree',
      type: 'url',
      description:
        'Załóż darmowy formularz na formspree.io (przekierowany na e-mail powyżej) i wklej tu adres, np. https://formspree.io/f/xxxxxx. Pusty = formularz kieruje do kontaktu telefonicznego.',
      group: 'contact',
    }),
    defineField({
      name: 'domain',
      title: 'Domena',
      type: 'string',
      group: 'general',
      initialValue: 'zjawiskowo.com.pl',
    }),
    defineField({
      name: 'footerNote',
      title: 'Nota w stopce (polityka prywatności / cookies)',
      type: 'text',
      rows: 2,
      group: 'general',
    }),
  ],
  preview: {
    prepare: () => ({ title: 'Ustawienia salonu' }),
  },
})
