import { defineType, defineField } from 'sanity'

export const siteSettings = defineType({
  name: 'siteSettings',
  title: 'Ustawienia salonu',
  type: 'document',
  groups: [
    { name: 'general', title: 'Ogólne' },
    { name: 'hero', title: 'Sekcja główna (hero)' },
    { name: 'home', title: 'Strona główna — sekcje' },
    { name: 'subpages', title: 'Podstrony — nagłówki' },
    { name: 'promo', title: 'Pasek promocji' },
    { name: 'contact', title: 'Kontakt' },
  ],
  fields: [
    defineField({
      name: 'salonName',
      title: 'Nazwa salonu',
      type: 'string',
      group: 'general',
      initialValue: 'ZJAWISKOWO',
    }),
    defineField({
      name: 'salonSubtitle',
      title: 'Podpis pod nazwą (nagłówek i stopka)',
      description:
        'Widoczny pod logo w nagłówku i w stopce. Tu trafia informacja o depilacji laserowej.',
      type: 'string',
      group: 'general',
      initialValue: 'Salon kosmetyczny · Depilacja laserowa',
    }),
    defineField({
      name: 'theme',
      title: 'Wariant kolorystyczny',
      type: 'string',
      group: 'general',
      options: {
        list: [
          { title: 'Złota elegancja', value: 'gold' },
          { title: 'Lawendowy blask', value: 'lavender' },
          { title: 'Świetlista biel', value: 'white' },
        ],
        layout: 'radio',
      },
      initialValue: 'gold',
    }),
    defineField({
      name: 'heroKicker',
      title: 'Nadtytuł',
      type: 'string',
      group: 'hero',
      initialValue: 'Salon kosmetyczny · Depilacja laserowa · Krzeszowice',
    }),
    defineField({
      name: 'tagline',
      title: 'Hasło główne',
      type: 'string',
      group: 'hero',
      initialValue: 'Piękno zaczyna się tutaj',
    }),
    defineField({
      name: 'heroLead',
      title: 'Opis pod hasłem',
      type: 'text',
      rows: 2,
      group: 'hero',
    }),
    defineField({
      name: 'heroFaceImage',
      title: 'Zdjęcie — kosmetyka twarzy',
      type: 'image',
      options: { hotspot: true },
      group: 'hero',
    }),
    defineField({
      name: 'heroLaserImage',
      title: 'Zdjęcie — depilacja laserowa',
      type: 'image',
      options: { hotspot: true },
      group: 'hero',
    }),
    defineField({
      name: 'heroMainImage',
      title: 'Zdjęcie główne (wariant „Świetlista biel")',
      type: 'image',
      options: { hotspot: true },
      group: 'hero',
    }),
    defineField({
      name: 'heroSlides',
      title: 'Slajdy hero (wariant „Lawendowy blask")',
      type: 'array',
      of: [{ type: 'image', options: { hotspot: true } }],
      group: 'hero',
    }),
    defineField({
      name: 'pillarsKicker',
      title: 'Nadtytuł sekcji „Zabiegi”',
      type: 'string',
      group: 'home',
      initialValue: 'Oferta salonu',
    }),
    defineField({
      name: 'pillarsHeading',
      title: 'Nagłówek sekcji „Zabiegi”',
      type: 'string',
      group: 'home',
      initialValue: 'Dwa filary ZJAWISKOWO',
    }),
    defineField({
      name: 'pillarsLead',
      title: 'Opis sekcji „Zabiegi”',
      type: 'text',
      rows: 2,
      group: 'home',
    }),
    defineField({
      name: 'trustKicker',
      title: 'Nadtytuł sekcji „Dlaczego ZJAWISKOWO”',
      type: 'string',
      group: 'home',
      initialValue: 'Dlaczego ZJAWISKOWO',
    }),
    defineField({
      name: 'trustHeading',
      title: 'Nagłówek sekcji „Dlaczego ZJAWISKOWO”',
      type: 'string',
      group: 'home',
      initialValue: 'Co wyróżnia mój salon',
    }),
    defineField({
      name: 'showTrust',
      title: 'Pokaż sekcję „Dlaczego ZJAWISKOWO”',
      description: 'Punkty dodajesz w panelu, w sekcji „Dlaczego ZJAWISKOWO”.',
      type: 'boolean',
      group: 'home',
      initialValue: true,
    }),
    defineField({
      name: 'reviewsKicker',
      title: 'Nadtytuł sekcji „Opinie”',
      type: 'string',
      group: 'home',
      initialValue: 'Opinie klientek',
    }),
    defineField({
      name: 'reviewsHeading',
      title: 'Nagłówek sekcji „Opinie”',
      type: 'string',
      group: 'home',
      initialValue: 'Co mówią klientki',
    }),
    defineField({
      name: 'showReviews',
      title: 'Pokaż karuzelę opinii',
      description:
        'Wyłączenie ukrywa całą sekcję z opiniami, bez kasowania czegokolwiek. Opinie NIE pobierają się automatycznie z wizytówki Google — dodajesz je ręcznie w sekcji „Opinie”, a pojedynczą ukrywasz przełącznikiem przy niej.',
      type: 'boolean',
      group: 'home',
      initialValue: true,
    }),
    defineField({
      name: 'reviewsNote',
      title: 'Dopisek pod opiniami',
      type: 'string',
      group: 'home',
      description:
        'Zostaw „Opinie pochodzą z wizytówki Google” tylko wtedy, gdy faktycznie przepisujesz opinie z Google. Jeśli wpisujesz własne, wyczyść to pole — inaczej strona twierdzi coś nieprawdziwego.',
      initialValue: 'Opinie pochodzą z wizytówki Google',
    }),
    defineField({
      name: 'googleReviewUrl',
      title: 'Link do wystawienia opinii w Google',
      description:
        'Adres, pod którym klientka wystawia opinię w wizytówce Google. Używany pod karuzelą opinii i do wygenerowania kodu QR do druku.',
      type: 'url',
      group: 'home',
    }),
    defineField({
      name: 'galleryKicker',
      title: 'Nadtytuł sekcji „Galeria”',
      type: 'string',
      group: 'home',
      initialValue: 'Galeria',
    }),
    defineField({
      name: 'galleryHeading',
      title: 'Nagłówek sekcji „Galeria”',
      type: 'string',
      group: 'home',
      initialValue: 'Wnętrze salonu',
    }),
    defineField({
      name: 'showGallery',
      title: 'Pokaż galerię na stronie głównej',
      type: 'boolean',
      group: 'home',
      initialValue: true,
    }),
    defineField({
      name: 'showFaq',
      title: 'Pokaż sekcję FAQ na stronie głównej',
      type: 'boolean',
      group: 'home',
      initialValue: true,
    }),
    defineField({
      name: 'faqKicker',
      title: 'Nadtytuł sekcji „FAQ”',
      type: 'string',
      group: 'home',
      initialValue: 'Najczęstsze pytania',
    }),
    defineField({
      name: 'faqHeading',
      title: 'Nagłówek sekcji „FAQ”',
      type: 'string',
      group: 'home',
      initialValue: 'FAQ',
    }),
    defineField({
      name: 'faqCtaLabel',
      title: 'Przycisk pod pytaniami',
      type: 'string',
      group: 'home',
      description: 'Prowadzi na stronę Kontakt. Puste pole ukrywa przycisk.',
      initialValue: 'Masz inne pytanie? Napisz do mnie',
    }),
    defineField({
      name: 'priceTeaserKicker',
      title: 'Nadtytuł sekcji „Cennik w skrócie”',
      type: 'string',
      group: 'home',
      initialValue: 'Cennik w skrócie',
    }),
    defineField({
      name: 'priceTeaserHeading',
      title: 'Nagłówek sekcji „Cennik w skrócie”',
      type: 'string',
      group: 'home',
      initialValue: 'Ceny i pakiety',
    }),
    defineField({
      name: 'ctaHeading',
      title: 'Nagłówek sekcji z telefonem',
      type: 'string',
      group: 'home',
      initialValue: 'Umów wizytę',
    }),
    defineField({
      name: 'ctaKicker',
      title: 'Nadtytuł sekcji z telefonem',
      type: 'string',
      group: 'home',
      initialValue: 'Rezerwacja tylko telefoniczna',
    }),
    defineField({
      name: 'ctaLead',
      title: 'Opis sekcji z telefonem',
      type: 'text',
      rows: 2,
      group: 'home',
    }),
    defineField({
      name: 'ctaHint',
      title: 'Dopisek pod numerem telefonu',
      type: 'string',
      group: 'home',
      description: 'Puste pole ukrywa dopisek.',
      initialValue: 'Nie odbieram, gdy trwa zabieg. Oddzwonię, gdy tylko skończę.',
    }),

    /* ── Podstrony ──────────────────────────────────────────────────────
       Nagłówki i wezwania na stronach, które nie mają własnego dokumentu
       z treścią (lista zabiegów, kontakt).                              */
    defineField({
      name: 'treatmentsHeading',
      title: 'Zabiegi — nagłówek strony',
      type: 'string',
      group: 'subpages',
      description: 'Nadtytuł i opis tej strony biorą się z sekcji „Zabiegi” na stronie głównej.',
      initialValue: 'Moje zabiegi',
    }),
    defineField({
      name: 'treatmentsCtaKicker',
      title: 'Zabiegi — nadtytuł sekcji z telefonem',
      type: 'string',
      group: 'subpages',
      initialValue: 'Nie wiesz, co wybrać?',
    }),
    defineField({
      name: 'treatmentsCtaHeading',
      title: 'Zabiegi — nagłówek sekcji z telefonem',
      type: 'string',
      group: 'subpages',
      initialValue: 'Zadzwoń — doradzę podczas konsultacji',
    }),
    defineField({
      name: 'showPromo',
      title: 'Pokaż pasek promocji',
      description:
        'Wyłączenie chowa złoty pasek pod menu na wszystkich stronach. Treść zostaje zapisana, więc możesz go włączyć z powrotem przy kolejnej promocji.',
      type: 'boolean',
      group: 'promo',
      initialValue: true,
    }),
    defineField({
      name: 'promoText',
      title: 'Treść promocji',
      type: 'string',
      group: 'promo',
      description: 'Pasek nie pokaże się, dopóki to pole jest puste.',
    }),
    defineField({
      name: 'contactKicker',
      title: 'Kontakt — nadtytuł strony',
      type: 'string',
      group: 'contact',
      initialValue: 'Kontakt',
    }),
    defineField({
      name: 'contactHeading',
      title: 'Kontakt — nagłówek strony',
      type: 'string',
      group: 'contact',
      initialValue: 'Odwiedź mnie w Krzeszowicach',
    }),
    defineField({
      name: 'contactLead',
      title: 'Kontakt — wprowadzenie',
      type: 'text',
      rows: 3,
      group: 'contact',
      initialValue:
        'Rezerwacja wyłącznie telefoniczna — zadzwoń, a wspólnie ustalimy dogodny termin. Poniżej znajdziesz adres, godziny i dojazd.',
    }),
    defineField({
      name: 'phone',
      title: 'Telefon',
      type: 'string',
      group: 'contact',
      initialValue: '517 899 229',
    }),
    defineField({
      name: 'address',
      title: 'Adres',
      type: 'string',
      group: 'contact',
    }),
    defineField({
      name: 'hours',
      title: 'Godziny otwarcia',
      type: 'string',
      group: 'contact',
    }),
    defineField({
      name: 'contactNotes',
      title: 'Udogodnienia / wskazówki dojazdu',
      type: 'array',
      of: [{ type: 'string' }],
      group: 'contact',
      description: 'Np. „Bezpłatny parking”, „Budynek przy automyjni”.',
    }),
    defineField({
      name: 'facebookUrl',
      title: 'Facebook (URL)',
      type: 'url',
      group: 'contact',
    }),
    defineField({
      name: 'instagramUrl',
      title: 'Instagram (URL)',
      type: 'url',
      group: 'contact',
    }),
    defineField({
      name: 'googleMapsEmbedUrl',
      title: 'Mapa Google — adres osadzenia (embed URL)',
      type: 'url',
      group: 'contact',
    }),
    // Pola formularza (adres Formspree, e-mail kontaktowy, dopisek nad
    // formularzem) zniknęły 4 sierpnia razem z samym formularzem — klientka
    // nie chce korespondencji mailowej, jedyną drogą kontaktu jest telefon.
    // Wartości zostają w zbiorze danych, ale nie ma ich już w panelu ani
    // w zapytaniu, żeby nie sugerowały funkcji, której strona nie ma.
    defineField({
      name: 'domain',
      title: 'Domena',
      type: 'string',
      group: 'general',
      initialValue: 'zjawiskowo.com.pl',
    }),
    defineField({
      name: 'footerNote',
      title: 'Nota w stopce (polityka prywatności / cookies)',
      type: 'text',
      rows: 2,
      group: 'general',
    }),
  ],
  preview: {
    prepare: () => ({ title: 'Ustawienia salonu' }),
  },
})
